spring.application.name=bookstore
spring.profiles.active=local-postgre
#spring.jpa.show-sql=true
#spring.data.rest.base-path=/api
#spring.datasource.url=jdbc:postgresql://localhost:5432/k26bookstore
#spring.datasource.username=postgre
#spring.datasource.password=Ganiinit
