spring.application.name=harjoitustyo
spring.profiles.active=local-postgre
spring.jpa.show-sql=true
spring.data.rest.base-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/harjoitustyo
spring.datasource.username=postgres
spring.datasource.password=Ganiinit
 
#JPA/hibernate ei tee muutoksia ulkoiseen kantaan none arvolla
spring.jpa.hibernate.ddl-auto=none